#include "varblockspmm/vbsr.hpp"
#include <cuda_runtime.h>
#include <cmath>
#include <iostream>
#include <random>
#include <stdexcept>
#include <string>

static void compare(const std::vector<float>&ref,float*dc,const char*name){std::vector<float>got(ref.size());cudaMemcpy(got.data(),dc,got.size()*sizeof(float),cudaMemcpyDeviceToHost);double mx=0,l2=0,den=0;for(size_t i=0;i<got.size();i++){if(!std::isfinite(got[i]))throw std::runtime_error(std::string(name)+" produced NaN/Inf");double d=got[i]-ref[i];mx=std::max(mx,std::abs(d));l2+=d*d;den+=double(ref[i])*ref[i];}double rel=std::sqrt(l2/(den+1e-30));if(mx>5e-4||rel>5e-5)throw std::runtime_error(std::string(name)+" mismatch: max="+std::to_string(mx)+", rel="+std::to_string(rel));}
static void run_case(vbsr::Distribution dist,int degree,int rhs,bool local,uint64_t seed){vbsr::GeneratorOptions o;o.block_rows=9;o.block_cols=17;o.degree=degree;o.distribution=dist;o.local_columns=local;o.seed=seed;auto h=vbsr::generate(o);std::vector<float>b(h.scalar_cols()*rhs);std::mt19937 g{unsigned(seed)};for(auto&x:b)x=std::uniform_real_distribution<float>(-1,1)(g);auto ref=vbsr::cpu_reference(h,b,rhs);vbsr::Matrix a(h);float *db,*dc;cudaMalloc(&db,b.size()*sizeof(float));cudaMalloc(&dc,ref.size()*sizeof(float));cudaMemcpy(db,b.data(),b.size()*sizeof(float),cudaMemcpyHostToDevice);cudaStream_t stream;cudaStreamCreate(&stream);vbsr::Plan direct(a,{rhs,vbsr::Kernel::RowOwned});vbsr::ScalarCsrPlan csr(h,rhs);vbsr::GroupedGemmPlan grouped(h,rhs);direct.execute(db,dc,stream);cudaStreamSynchronize(stream);compare(ref,dc,"row-owned ILP");vbsr::launch_row_owned_scalar(a.device_view(),db,dc,rhs,stream);cudaStreamSynchronize(stream);compare(ref,dc,"row-owned scalar");csr.execute(db,dc,stream);cudaStreamSynchronize(stream);compare(ref,dc,"cuSPARSE");grouped.execute(db,dc,stream);cudaStreamSynchronize(stream);compare(ref,dc,"grouped cuBLAS");cudaStreamDestroy(stream);cudaFree(db);cudaFree(dc);}
static void negative_tests(){vbsr::GeneratorOptions o;o.block_rows=4;o.block_cols=4;o.degree=2;auto h=vbsr::generate(o);auto bad=h;bad.row_ptr.back()++;bool rejected=false;try{bad.validate();}catch(const std::invalid_argument&){rejected=true;}if(!rejected)throw std::runtime_error("malformed row_ptr accepted");vbsr::Matrix a(h);rejected=false;try{vbsr::Plan p(a,{7,vbsr::Kernel::RowOwned});}catch(const std::invalid_argument&){rejected=true;}if(!rejected)throw std::runtime_error("invalid RHS accepted");rejected=false;try{vbsr::Plan p(a,{8,vbsr::Kernel::SplitRow});}catch(const std::invalid_argument&){rejected=true;}if(!rejected)throw std::runtime_error("unjustified split-row accepted");}
int main(){try{negative_tests();uint64_t seed=11;for(auto d:{vbsr::Distribution::Uniform,vbsr::Distribution::LowVariance,vbsr::Distribution::HighVariance,vbsr::Distribution::Bimodal})for(int degree:{1,4,8,16})for(int rhs:{8,16,32,64})run_case(d,degree,rhs,(seed&1)!=0,seed++);std::cout<<"PASS: 64 parameter cases x hybrid/scalar/cuSPARSE/grouped paths, non-default streams, validation failures, NaN/Inf checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL: "<<e.what()<<"\n";return 1;}}
